paris_wifi_dbt:
  outputs:
    dev:
      dataset: paris_wifi_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /key.json
      location: EU
      method: service-account
      priority: interactive
      project: round-fold-449120-g9
      threads: 1
      type: bigquery
  target: dev
