# docker/Dockerfile.pandas

FROM python:3.12-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir pandas unidecode

# Copy your script
COPY ingestion/datasplit.py .

# Set default entrypoint
ENTRYPOINT ["python", "datasplit.py"]