# docker/Dockerfile.python

FROM python:3.12-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir pandas unidecode

# Copy script and data
COPY ingestion/datasplit.py .
COPY data/ ./data/

# Set default entrypoint
ENTRYPOINT ["python", "datasplit.py"]